version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    #restart: always
    restart: unless-stopped    
    hostname: 'gitlab.neolant-srv.ru'
    environment:
      GITLAB_HOME:
        $HOME/My_Projects/Docker/app_gitlab/GITLAB_HOME
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.neolant-srv.ru'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '8080:8080'
      - '443:443'
      - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
